//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doyur.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderProductList = new HashSet<OrderProductList>();
        }
    
        public int OrderId { get; set; }
        public int CompanyId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public byte Status { get; set; }
        public string Coupon { get; set; }
        public bool IsActive { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProductList> OrderProductList { get; set; }
        public virtual Users Users { get; set; }
    }
}
