//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doyur.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Address = new HashSet<Address>();
            this.Company = new HashSet<Company>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int UserId { get; set; }
        public byte AccessId { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Phone { get; set; }
        public string Gsm { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public string Note { get; set; }
        public byte Gender { get; set; }
        public System.DateTime BrithDate { get; set; }
        public string Path { get; set; }
        public string Activation { get; set; }
        public bool IsName { get; set; }
        public bool IsPhone { get; set; }
        public bool IsGsm { get; set; }
        public bool IsPath { get; set; }
        public bool IsActivation { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
